@GoaledSchedules = new Meteor.Collection "goaledSchedules"
@Classes         = new Meteor.Collection "classes"
@Schools         = new Meteor.Collection "schools"
@Schedules       = new Meteor.Collection "schedules"
@Votes           = new Meteor.Collection "votes"
@Utils           = new Meteor.Collection "utils"
@Tickets         = new Meteor.Collection "tickets"
@Projects        = new Meteor.Collection "projects"
@CalendarItems   = new Meteor.Collection "calendarItems"

@BetaPeople = new Meteor.Collection "betaPeople"
